
name: 'dbt_demo_project'              # Your project name
version: '1.0'
config-version: 2                   # Always use version 2 for new projects

profile: 'profiles'           # Matches your ~/.dbt/profiles.yml profile

target-path: "target"               # Where dbt will write compiled SQL
clean-targets:                      # Folders to clean when you run `dbt clean`
  - "target"
  - "dbt_modules"

model-paths: ["models"]             # Where your models live
analysis-paths: ["analyses"]        # Optional: for ad-hoc analysis SQL files
test-paths: ["tests"]               # Optional: if you write custom tests
macro-paths: ["macros"]             # Optional: for macros

models:
  my_dbt_project:                    # Namespace for your project models
    +materialized: table             # Default materialization (table, view, incremental)
    example:                         # Optional subfolder settings
      +materialized: view            # Override default materialization for models in models/example
