version: 2

sources:
  - name: raw_yahoo
    database: dbt-demo-project-485817   # Your GCP project
    schema: raw_yahoo                     # BigQuery dataset

    tables:
      - name: raw_yahoo_prices
        description: "Raw daily stock prices ingested from Yahoo Finance"
        
        # Column that tracks when the row was ingested
        loaded_at_field: ingestion_timestamp

        # Freshness thresholds
        freshness:
          warn_after:
            count: 2
            period: day
          error_after:
            count: 7
            period: day

        # Basic column tests
        columns:
          - name: symbol
            description: "Stock ticker symbol"
            tests:
              - not_null

          - name: trading_date
            description: "Date of the trading session"
            tests:
              - not_null

          - name: close
            description: "Closing price for the day"
            tests:
              - not_null
